name = "Rad Pack 2024"
author = "Aero48"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6e7fd816e2e00ad29f04787723d2dd90f3c0282edb735751e1e724c9cf6cf0b"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
