name = "Rad Pack 2024"
author = "Aero48"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d13cf59ce08567020e2d274d23c823bf194b08db17c43f8abaea59f03c48d348"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
